@baseUrl = http://localhost:8000/api

### Register
# @name register
POST {{ baseUrl }}/auth/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "prueba2@prueba.com",
    "password": "Grp$4cFqas789",
    "name": "test2"
}


### Login   
# @name Login
POST {{ baseUrl }}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "prueba@prueba.com",
    "password": "Grp$4cFqas789"
}